### ISSUE TITLE
custom Validator function called whenever another input is changed?

### ISSUE THREAD

**Issue by alewiahmed** [monterail/vuelidate#144]
First of all I really like this plugin, it' fantastic. I've used the same code for another project & it was doing great. When I used it on another project it is acting weird. The only difference between the two projects is that the old one was using Vuelidate V0.3.1 & the new one is using Vuilidate V0.4.3.

I use a custom function to check if a username is unique or not. first I check if the email validator is passed then I check if the email is unique. Long story short, when I change another input field the isUnique validator of the username field is called. that's weird. When I remove the this.$v.username.email check, everything is back to normal. When I even console.log(this.$v.username.email), inside the isUnique validator the weird behavior happens.

username: {
    	required,
      email,
      isUnique: function () {
      console.log(this.$v.username.email)
      console.log('isUnique called')
      return true
    }
    },
    name: {
    required
  }

For the above code, the isUnique function is called whenever the name field is changed. If I remove the console.log(this.$v.username.email) call it doesn't call the function. Why is that?

here is a fiddle for the above code. https://jsfiddle.net/alewiahmed/1uncLw33/

All the above behavior doesn't happen on V0.3.1.

**Comment by desjoerd** [comment]
I think this is because $v is a Vue instance which changes, by accessing a variable on $v you create a watcher (all validations are computed getters).

**Comment by alewiahmed** [comment]
You know, it used to work perfectly at v0.3.1. Now when you change one field, the custom validator function of **another field** is called. That shouldn't happen.

**Comment by desjoerd** [comment]
It gives the expected behaviour when  you nest them both.
https://jsfiddle.net/1uncLw33/6/

**Comment by alewiahmed** [comment]
Thanks for your fast replies @desjoerd , I really appreciate it. I saw https://jsfiddle.net/1uncLw33/6/ it works fine, but I have two main concerns, 
1. Your will have to nest fields even if you don't need then.
2. Still when the test field is changed the isUnique function is called.

You can use the nesting to bypass the issue but that doesn't make the issue go away. if this is supposed to be a normal behavior, I is not good, It was perfect a v0.3.1. If this is a bug, it needs fixing.

**Comment by desjoerd** [comment]
I suppose it's a bug. I am just a humble user of vuelidate. It must be something how the computed properties are computed. The issue starts when you use a property on $v. Which is a proxy to a Vue component. Another solution if you don't want to nest your properties is to call the email validator inside isUnique instead of relying on $v. Maybe someone of Monterail can give some directions to solve this issue

**Comment by alewiahmed** [comment]
Thanks @desjoerd, your help is very much appreciated. You know, I just downgraded to 0.3.1 because its working as expected. May be I'll check to source code & see what's going on.

**Comment by Frizi** [comment]
Right, this looks like a bug, and that's a pretty complex one. Somehow there is a crosstalk of data dependencies in case when you reference the validation object itself inside a validation function. On the other hand that's already a wonder it works, as you are very close to creating a dependency cycle here. I will look into that, but it might be hard one to track down. Going back to 0.3.1 gives you many other list tracking bugs, so I would advice to avoid that if not necessary. Actually that might be a legit dependency (yeah, our intuitions fail us every day) that was not picked up because of that old bug.

As a workaround, can you explain why are you trying to reference different validation inside validator? Maybe there is simply a more straight-forward solution that would simply avoid that behaviour.

**Comment by alewiahmed** [comment]
@Frizi I'm glad you've added a commit for this issue. To answer your questions on why I need to reference different validation inside a validator, I am working on a registration page & I wanted to check if the given email is already registered or not. that's one validation. inside this validation, I didn't want to call the server whenever the user types something, so what I did was check if the input is email first before it sending a server request. So that's why I use a validation inside another validator. I hope that's clear.

**Comment by Frizi** [comment]
@alewiahmed The issue is not yet resolved, you shouldn't close it. It will be once it lands in master at least. PR is still missing some testing coverage, and that have to be fixed before merging. Feel free to use the branch as it is though, and a feedback if it works for you would also be appreciated.

**Comment by alewiahmed** [comment]
I'll check it out and let you know.

**Comment by kevingermain** [comment]
Such a big problem that I can't resolve and I have to... Please try to fix it soon if it's possible. Thank you so much.

**Comment by Frizi** [comment]
fix merged to master, will be released with next release

**Comment by Liioo** [comment]
With the exactly same validations of @alewiahmed , I'm still having this problem.

When editing an input, not only his validations are fired, but all others declared in `validations: {}` from others inputs too.

Using Vuelidate **0.7.4**

**Comment by travis-anderson** [comment]
I am also still having this problem with Vuelidate 0.7.4

**Comment by ahmadmu** [comment]
Is there a fix for this problem yet? Also having it with 0.7.5
